Repository KillianLucas/open-interpreter, pull requests merged in 2023-11, with the labels that each got.

#727 Update README.md for sample FastAPI
  README.md
Labels: reviewed

#725 Update MACOS.md: fix command
  docs/MACOS.md
Labels: reviewed

#712 update Readme_ZH.md
  README_ZH.md
Labels: documentation, help wanted

#701 Get more system info in debug mode
  interpreter/llm/setup_llm.py
  interpreter/terminal_interface/terminal_interface.py
  interpreter/utils/system_debug_info.py
  pyproject.toml
Labels: reviewed

#750 Added more useful info to system info
  interpreter/terminal_interface/terminal_interface.py
  interpreter/utils/system_debug_info.py
Labels: reviewed

#742 chore: popen using utf8 encoding
  interpreter/code_interpreters/subprocess_code_interpreter.py
Labels: reviewed

#476 MOD: close subprocess and its file handles when reset
  interpreter/code_interpreters/subprocess_code_interpreter.py
Labels: pre-refactor

#738 Create README_DE.md
  README_DE.md
Labels: documentation, help wanted
